// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BottomControls: typeof import('./src/components/BottomControls.vue')['default']
    HeaderBar: typeof import('./src/components/HeaderBar.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    Timer: typeof import('./src/components/Timer.vue')['default']
    TimerList: typeof import('./src/components/TimerList.vue')['default']
    TopControls: typeof import('./src/components/TopControls.vue')['default']
  }
}
